name: quran_learning_1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.7+8

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2



  # The following adds the Cupertino Icons fonts to your application.
  # Use with the CupertinoIcons class for iOS theme icons.
  cupertino_icons: ^1.0.2
  flutter_svg:
  flutter_bloc:
  flame: ^1.0.0
  playing_cards:
  lottie: ^3.1.0
  sprung:
  video_player:
  url_launcher:

  #Dream Home packages
  octo_image: ^2.0.0
  flutter_blurhash: ^0.8.2
  cached_network_image: ^3.2.0
  dotted_border: ^2.1.0
  pin_code_fields:
  font_awesome_flutter: ^10.2.1
  carousel_slider: ^4.0.0

  #FurnitureHub packages
  connectivity_plus: ^5.0.2

  #Go Ride packages
  google_maps_flutter:
  syncfusion_flutter_calendar:
  flutter_time_picker_spinner:
  dotted_line:
  flutter_rating_bar:
  simple_animations:

  #Meditation app
  just_audio:

  #LoveMeet app
  swipe_cards: ^2.0.0+1
  card_swiper: ^3.0.1
  country_code_picker: ^3.0.0
  sms_autofill: ^2.3.0

  #PlayMedia app
  percent_indicator: ^4.2.3

  #Food master app
  shared_preferences: ^2.0.13
  image: ^4.1.7

  #Crypto Tech App
  websafe_svg: ^3.0.1+1
  webview_flutter: ^4.5.0
  flutter_html: ^3.0.0-alpha.3
  file_picker: ^6.2.0

  #Happy shop app
  flutter_staggered_grid_view:
  like_button: ^2.0.5

  #News app
  flutter_snake_navigationbar: ^0.6.1
  flutter_slidable: ^3.0.1
  photo_view: ^0.14.0

  #doctorApp
  country_picker: ^2.0.24
  google_fonts: ^6.1.0
  image_picker: ^1.0.7

  #Fitness app
  circular_countdown_timer: ^0.2.3
  flutter_date_picker_timeline: ^0.3.3
  youtube_player_flutter: ^9.0.0
  syncfusion_flutter_charts: ^25.1.35


  #Modern news app
  provider: any

  #NFT app
  smooth_page_indicator: ^1.1.0

  #Hotel booking app
  pinput: ^4.0.0
  syncfusion_flutter_datepicker: ^25.1.35
  #music app
  sleek_circular_slider: ^2.0.1

dependency_overrides:
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  change_app_package_name: ^1.0.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons fonts is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/


    #Full apps assets
    - assets/images/avatar/
    - assets/images/pagination/


  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the fonts family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the fonts. For
  # example:
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800

    - family: datingappfonts
      fonts:
        - asset: assets/fonts/KoHo-Light.ttf
          weight: 300
        - asset: assets/fonts/KoHo-Regular.ttf
          weight: 400
        - asset: assets/fonts/KoHo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/KoHo-Bold.ttf
          weight: 700
        - asset: assets/fonts/KoHo-BoldItalic.ttf
        - asset: assets/fonts/KoHo-ExtraLight.ttf
        - asset: assets/fonts/KoHo-ExtraLightItalic.ttf
        - asset: assets/fonts/KoHo-Italic.ttf
        - asset: assets/fonts/KoHo-LightItalic.ttf
        - asset: assets/fonts/KoHo-Medium.ttf
        - asset: assets/fonts/KoHo-MediumItalic.ttf
        - asset: assets/fonts/KoHo-SemiBoldItalic.ttf

    - family: Myfonts
      fonts:
        - asset: assets/fonts/SFUIText-Regular.ttf
        - asset: assets/fonts/SFUIText-Bold.ttf
          weight: 700

    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue.ttf

    - family: SFPro
      fonts:
        - asset: assets/fonts/SFProRegular.ttf

    - family: salonfonts
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700


    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
    - family: TrebuchetMS
      fonts:
        - asset: assets/fonts/TREBUC.TTF
        - asset: assets/fonts/TREBUCBD.TTF
          weight: 700
        - asset: assets/fonts/TREBUCBI.TTF
          weight: 700
          style: italic
        - asset: assets/fonts/TREBUCIT.TTF
          style: italic
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-LightItalic.ttf
          style: italic
          weight: 300
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic



  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
